/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2025 Inkdex */

export const LANGUAGE_NAMES_MAP: Record<string, string> = {
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  it: "Italian",
  pt: "Portuguese",
  ru: "Russian",
  ja: "Japanese",
  zh: "Chinese",
  ko: "Korean",
  ar: "Arabic",
  tr: "Turkish",
  pl: "Polish",
  nl: "Dutch",
  id: "Indonesian",
  th: "Thai",
  vi: "Vietnamese",
  hi: "Hindi",
  bn: "Bengali",
  ur: "Urdu",
  sw: "Swahili",
  mr: "Marathi",
  te: "Telugu",
  ta: "Tamil",
  gu: "Gujarati",
  fa: "Persian",
  uk: "Ukrainian",
  ml: "Malayalam",
  kn: "Kannada",
  or: "Odia",
  my: "Burmese",
  pa: "Punjabi",
  ro: "Romanian",
  hu: "Hungarian",
  el: "Greek",
  cs: "Czech",
  sv: "Swedish",
  fi: "Finnish",
  da: "Danish",
  no: "Norwegian",
  he: "Hebrew",
  sk: "Slovak",
  bg: "Bulgarian",
  hr: "Croatian",
  sr: "Serbian",
  lt: "Lithuanian",
  sl: "Slovenian",
  et: "Estonian",
  lv: "Latvian",
};

export const LANGUAGE_EMOJI_MAP: Record<string, string> = {
  en: "🇬🇧",
  es: "🇪🇸",
  fr: "🇫🇷",
  de: "🇩🇪",
  it: "🇮🇹",
  pt: "🇵🇹",
  ru: "🇷🇺",
  ja: "🇯🇵",
  zh: "🇨🇳",
  ko: "🇰🇷",
  ar: "🇸🇦",
  tr: "🇹🇷",
  pl: "🇵🇱",
  nl: "🇳🇱",
  id: "🇮🇩",
  th: "🇹🇭",
  vi: "🇻🇳",
  hi: "🇮🇳",
  bn: "🇧🇩",
  ur: "🇵🇰",
  sw: "🇰🇪",
  mr: "🇮🇳",
  te: "🇮🇳",
  ta: "🇮🇳",
  gu: "🇮🇳",
  fa: "🇮🇷",
  uk: "🇺🇦",
  ml: "🇮🇳",
  kn: "🇮🇳",
  or: "🇮🇳",
  my: "🇲🇲",
  pa: "🇮🇳",
  ro: "🇷🇴",
  hu: "🇭🇺",
  el: "🇬🇷",
  cs: "🇨🇿",
  sv: "🇸🇪",
  fi: "🇫🇮",
  da: "🇩🇰",
  no: "🇳🇴",
  he: "🇮🇱",
  sk: "🇸🇰",
  bg: "🇧🇬",
  hr: "🇭🇷",
  sr: "🇷🇸",
  lt: "🇱🇹",
  sl: "🇸🇮",
  et: "🇪🇪",
  lv: "🇱🇻",
};

export const VALID_IETF_LANGUAGE_TAGS = new Set([
  ...Object.keys(LANGUAGE_EMOJI_MAP),
  "multi",
]);
